// components/ScrollToTop.tsx
'use client'

import { useScroll } from '../hooks/useScroll'
import { smoothScrollTo } from '../utils/scrollUtils'

export default function ScrollToTop() {
  const { isScrolled } = useScroll()

  const scrollToTop = () => {
    smoothScrollTo('page-top')
  }

  return (
    <div 
      className={`scroll-to-top d-lg-none position-fixed ${isScrolled ? 'd-block' : 'd-none'}`}
      style={{
        opacity: isScrolled ? 1 : 0,
        transition: 'opacity 0.3s ease-in-out'
      }}
    >
      <button 
        className="d-block text-center text-white rounded border-0 w-100 h-100"
        onClick={scrollToTop}
        style={{
          background: 'rgba(26, 188, 156, 0.8)',
          width: '2.5rem',
          height: '2.5rem',
          position: 'fixed',
          bottom: '1rem',
          right: '1rem',
          borderRadius: '50%',
          cursor: 'pointer'
        }}
        aria-label="Scroll to top"
      >
        <i className="fa fa-chevron-up"></i>
      </button>
    </div>
  )
}

// components/ScrollToTop.vue
<template>
  <button 
    v-show="showButton"
    @click="scrollToTop"
    class="scroll-to-top position-fixed"
    :style="{ bottom: '15px', right: '15px' }"
  >
    <i class="fa fa-chevron-up"></i>
  </button>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const showButton = ref(false)

const handleScroll = () => {
  showButton.value = window.scrollY > 400
}

const scrollToTop = () => {
  window.scrollTo({
    top: 0,
    behavior: 'smooth'
  })
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
  handleScroll()
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<style scoped>
.scroll-to-top {
  width: 50px;
  height: 50px;
  text-align: center;
  color: #fff;
  background: rgba(90, 92, 105, .5);
  line-height: 45px;
  z-index: 1049;
  border: none;
  border-radius: 4px;
  transition: all 0.3s;
  cursor: pointer;
}

.scroll-to-top:hover {
  background: #5a5c69;
}

.scroll-to-top:focus {
  color: #fff;
  outline: none;
}
</style>
