// pages/index.vue
<template>
  <div>
    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
      <div class="container d-flex align-items-center flex-column">
        <NuxtImg class="masthead-avatar mb-5" src="/assets/img/salad.png" alt="Vegetarian Salad" width="200" height="200" />
        <h1 class="masthead-heading text-uppercase mb-0">vegetarian recipes</h1>
        <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-utensils"></i></div>
          <div class="divider-custom-line"></div>
        </div>
        <p class="masthead-subheading font-weight-light mb-0">
          This recipes will show you that becoming a vegetarian is not a missed steak
        </p>
      </div>
    </header>

    <!-- Basics Section -->
    <section class="page-section portfolio" id="basics" style="background-color: #8c271e">
      <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-white mb-0">Basics</h2>
        <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-leaf"></i></div>
          <div class="divider-custom-line"></div>
        </div>
        <div class="row justify-content-center">
          <RecipeModal
            v-for="(item, index) in recipes.basics"
            :key="index"
            :recipe="item.recipe"
            :filename="item.filename"
            type="basics"
            :github-repo="githubRepo"
          />
        </div>
      </div>
    </section>

    <!-- Portfolio Section -->
    <section class="page-section portfolio" id="portfolio">
      <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Savory</h2>
        <div class="divider-custom">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-carrot"></i></div>
          <div class="divider-custom-line"></div>
        </div>
        <div class="row justify-content-center">
          <RecipeModal
            v-for="(item, index) in recipes.savory"
            :key="index"
            :recipe="item.recipe"
            :filename="item.filename"
            type="savory"
            :github-repo="githubRepo"
          />
        </div>
      </div>
    </section>

    <!-- About Section -->
    <section class="page-section bg-primary text-white mb-0" id="about">
      <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-white">Sweet</h2>
        <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-candy-cane"></i></div>
          <div class="divider-custom-line"></div>
        </div>
        <div class="row justify-content-center">
          <RecipeModal
            v-for="(item, index) in recipes.sweet"
            :key="index"
            :recipe="item.recipe"
            :filename="item.filename"
            type="sweet"
            :github-repo="githubRepo"
          />
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import recipesData from '~/lib/data/recipes.json'

const config = useRuntimeConfig()
const githubRepo = config.public.githubRepo

const recipes = ref(recipesData)
</script>

// pages/index.tsx
import React from 'react';
import dynamic from 'next/dynamic';
import Image from 'next/image';
import { RecipesByCategory } from '../lib/types';
import recipesData from '../public/recipes.json';

const Layout = dynamic(() => import('../components/Layout'), { ssr: false });
const RecipeModal = dynamic(() => import('../components/RecipeModal'), { ssr: false });

export default function Home() {
  const recipes = recipesData as RecipesByCategory;
  const githubRepo = process.env.GITHUB_USERNAME_SLASH_REPO || 'magalipujol/missedSteak';
  return (
    <Layout title="Missed Steak - Vegetarian Recipes" githubRepo={githubRepo}>
      {/* Masthead */}
      <header className="masthead bg-primary text-white text-center">
        <div className="container d-flex align-items-center flex-column">
          <Image className="masthead-avatar mb-5" src="/assets/img/salad.png" alt="Vegetarian Salad" width={200} height={200} />
          <h1 className="masthead-heading text-uppercase mb-0">vegetarian recipes</h1>
          <div className="divider-custom divider-light">
            <div className="divider-custom-line"></div>
            <div className="divider-custom-icon"><i className="fas fa-utensils"></i></div>
            <div className="divider-custom-line"></div>
          </div>
          <p className="masthead-subheading font-weight-light mb-0">
            This recipes will show you that becoming a vegetarian is not a missed steak
          </p>
        </div>
      </header>

      {/* Basics Section */}
      <section className="page-section portfolio" id="basics" style={{ backgroundColor: '#8c271e' }}>
        <div className="container">
          <h2 className="page-section-heading text-center text-uppercase text-white mb-0">Basics</h2>
          <div className="divider-custom divider-light">
            <div className="divider-custom-line"></div>
            <div className="divider-custom-icon"><i className="fas fa-leaf"></i></div>
            <div className="divider-custom-line"></div>
          </div>
          <div className="row justify-content-center">
            {recipes.basics.map((item, index) => (
              <RecipeModal
                key={index}
                recipe={item.recipe}
                filename={item.filename}
                type="basics"
                githubRepo={githubRepo}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Portfolio Section */}
      <section className="page-section portfolio" id="portfolio">
        <div className="container">
          <h2 className="page-section-heading text-center text-uppercase text-secondary mb-0">Savory</h2>
          <div className="divider-custom">
            <div className="divider-custom-line"></div>
            <div className="divider-custom-icon"><i className="fas fa-carrot"></i></div>
            <div className="divider-custom-line"></div>
          </div>
          <div className="row justify-content-center">
            {recipes.savory.map((item, index) => (
              <RecipeModal
                key={index}
                recipe={item.recipe}
                filename={item.filename}
                type="savory"
                githubRepo={githubRepo}
              />
            ))}
          </div>
        </div>
      </section>

      {/* About Section */}
      <section className="page-section bg-primary text-white mb-0" id="about">
        <div className="container">
          <h2 className="page-section-heading text-center text-uppercase text-white">Sweet</h2>
          <div className="divider-custom divider-light">
            <div className="divider-custom-line"></div>
            <div className="divider-custom-icon"><i className="fas fa-candy-cane"></i></div>
            <div className="divider-custom-line"></div>
          </div>
          <div className="row justify-content-center">
            {recipes.sweet.map((item, index) => (
              <RecipeModal
                key={index}
                recipe={item.recipe}
                filename={item.filename}
                type="sweet"
                githubRepo={githubRepo}
              />
            ))}
          </div>
        </div>
      </section>
    </Layout>
  );
}
